server:
  port: 9004

spring:
  application:
    name: auth
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/CineSphere
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
  expiration: 20400
